export { Header } from './component/header/header'
export { LogIn } from './pages/login/login'
export { SignUp } from './pages/signup/signup'
export { Feed } from './pages/feed/feed'
export { CreateProfile } from './pages/onboard-profile/CreateProfile'
